import { Href } from "expo-router";

export type StaticAnimation = {
  appName: string;
  animationName: string;
  slug: string;
  href: Href;
};

export const STATIC_ANIMATIONS: StaticAnimation[] = [
  {
    animationName: "Juventus games calendar animation",
    appName: "Juventus",
    slug: "juventus-games-calendar-animation",
    href: "/juventus/home",
  },
  {
    animationName: "Apple Pay hold near reader animation",
    appName: "Apple Pay",
    slug: "apple-wallet-hold-near-reader-animation",
    href: "/apple-pay/home",
  },
  {
    animationName: "Product infinite carousel animation",
    appName: "Adidas",
    slug: "adidas-product-infinite-carousel-animation",
    href: "/adidas/product",
  },
  {
    animationName: "Nutrients circular carousel animation",
    appName: "Alma",
    slug: "alma-nutrients-circular-carousel-animation",
    href: "/alma/nutrients",
  },
  {
    animationName: "Text strikethrough animation",
    appName: "Superlist",
    slug: "superlist-text-strikethrough-animation",
    href: "/superlist/task",
  },
  {
    animationName: "Stories carousel animation",
    appName: "Instagram",
    slug: "instagram-stories-carousel-animation",
    href: "/instagram/stories",
  },
  {
    animationName: "Profile segmented control animation",
    appName: "Perplexity",
    slug: "perplexity-profile-segmented-control-animation",
    href: "/perplexity/profile",
  },
  {
    animationName: "Pull to refresh loading animation",
    appName: "Reddit",
    slug: "reddit-pull-to-refresh-loading-animation",
    href: "/reddit/home",
  },
  {
    animationName: "Moving dashed border animation",
    appName: "Opal",
    slug: "opal-moving-dashed-border-animation",
    href: "/opal/blocks",
  },
  {
    animationName: "Onboarding flow animation",
    appName: "Superlist",
    slug: "superlist-onboarding-flow-animation",
    href: "/superlist/onboarding",
  },
  {
    animationName: "Text input freeze on modal open animation",
    appName: "Perplexity",
    slug: "perplexity-text-input-freeze-on-modal-open-animation",
    href: "/perplexity/home",
  },
  {
    animationName: "Set timer slider animation",
    appName: "Opal",
    slug: "opal-set-timer-slider-animation",
    href: "/opal/home",
  },
  {
    animationName: "Home header animation",
    appName: "Perplexity",
    slug: "perplexity-home-header-animation",
    href: "/perplexity/home",
  },
  {
    animationName: "Onboarding animation",
    appName: "Longevity Deck",
    slug: "longevity-deck-onboarding-animation",
    href: "/longevity-deck/onboarding",
  },
  {
    animationName: "Chat input on focus animation",
    appName: "Perplexity",
    slug: "perplexity-chat-input-on-focus-animation",
    href: "/perplexity/chat",
  },
  {
    animationName: "Bottom sheet backdrop animation",
    appName: "Perplexity",
    slug: "perplexity-bottom-sheet-backdrop-animation",
    href: "/perplexity/home",
  },
  {
    animationName: "Header animation",
    appName: "App Store",
    slug: "app-store-header-animation",
    href: "/app-store/app",
  },
  {
    animationName: "Search screen open close animation",
    appName: "Linear",
    slug: "linear-search-screen-open-close-animation",
    href: "/linear/home",
  },
  {
    animationName: "Schedule timer tabs transition animation",
    appName: "Opal",
    slug: "opal-schedule-timer-tabs-transition-animation",
    href: "/opal/schedule",
  },
  {
    animationName: "Paywall upgrade button animation",
    appName: "Grok",
    slug: "grok-paywall-upgrade-button-animation",
    href: "/grok/paywall",
  },
  {
    animationName: "Paywall screen animation",
    appName: "Raycast",
    slug: "raycast-paywall-screen-animation",
    href: "/raycast/paywall",
  },
  {
    animationName: "Paywall screen animation",
    appName: "Grok",
    slug: "grok-paywall-screen-animation",
    href: "/grok/paywall",
  },
  {
    animationName: "Header on scroll animation",
    appName: "Linear",
    slug: "linear-header-on-scroll-animation",
    href: "/linear/home",
  },
  {
    animationName: "Horizontal carousel animation",
    appName: "Opal",
    slug: "opal-horizontal-carousel-animation",
    href: "/opal/blocks",
  },
  {
    animationName: "Start timer button animation",
    appName: "Opal",
    slug: "opal-start-timer-button-animation",
    href: "/opal/home",
  },
  {
    animationName: "Tabs shared header animation",
    appName: "Shopify",
    slug: "shopify-tabs-shared-header-animation",
    href: "/shopify/home",
  },
  {
    animationName: "Custom bottom tab bar animation",
    appName: "Shopify",
    slug: "shopify-custom-bottom-tab-bar-animation",
    href: "/shopify/home",
  },
  {
    animationName: "Menu transition animation",
    appName: "Shopify",
    slug: "shopify-menu-transition-animation",
    href: "/shopify/home",
  },
  {
    animationName: "Theme toggle animation",
    appName: "ColorsApp",
    slug: "colorsapp-theme-toggle-animation",
    href: "/colorsapp/home",
  },
  {
    animationName: "Search screen top tabs animation",
    appName: "Shopify",
    slug: "shopify-search-screen-top-tabs-animation",
    href: "/shopify/search",
  },
  {
    animationName: "Upgrade to pro modal animation",
    appName: "ColorsApp",
    slug: "colorsapp-upgrade-to-pro-modal-animation",
    href: "/colorsapp/paywall",
  },
  {
    animationName: "Blurry background animation",
    appName: "ColorsApp",
    slug: "colorsapp-blurry-background-animation",
    href: "/colorsapp/paywall",
  },
  {
    animationName: "Post truncated text animation",
    appName: "Instagram",
    slug: "instagram-post-truncated-text-animation",
    href: "/instagram/home",
  },
  {
    animationName: "Onboarding carousel animation",
    appName: "Alma",
    slug: "alma-onboarding-carousel-animation",
    href: "/alma/onboarding",
  },
  {
    animationName: "Attach file menu animation",
    appName: "Grok",
    slug: "grok-attach-file-menu-animation",
    href: "/grok/chat",
  },
  {
    animationName: "Upcoming list scroll animation",
    appName: "Showcase",
    slug: "showcase-upcoming-list-scroll-animation",
    href: "/showcase/upcoming",
  },
  {
    animationName: "Top tabs indicator animation",
    appName: "Discord",
    slug: "discord-top-tabs-indicator-animation",
    href: "/discord/account",
  },
  {
    animationName: "Button shimmer effect animation",
    appName: "Discord",
    slug: "discord-button-shimmer-effect-animation",
    href: "/discord/profile",
  },
  {
    animationName: "Custom switch animation",
    appName: "Discord",
    slug: "discord-custom-switch-animation",
    href: "/discord/clips",
  },
  {
    animationName: "Language radio button animation",
    appName: "Discord",
    slug: "discord-language-radio-button-animation",
    href: "/discord/language",
  },
  {
    animationName: "Shimmer text animation",
    appName: "ChatGPT",
    slug: "chatgpt-shimmer-text-animation",
    href: "/chatgpt/chat",
  },
  {
    animationName: "Header on scroll animation",
    appName: "Instagram",
    slug: "instagram-header-on-scroll-animation",
    href: "/instagram/home",
  },
  {
    animationName: "Catch up cards swipe animation",
    appName: "Slack",
    slug: "slack-catch-up-cards-swipe-animation",
    href: "/slack/catch-up",
  },
  {
    animationName: "Catch up header counter animation",
    appName: "Slack",
    slug: "slack-catch-up-header-counter-animation",
    href: "/slack/catch-up",
  },
  {
    animationName: "Info cards carousel animation",
    appName: "Fuse",
    slug: "fuse-info-cards-carousel-animation",
    href: "/fuse/home",
  },
  {
    animationName: "Balance secure view toggle animation",
    appName: "Fuse",
    slug: "fuse-balance-secure-view-toggle-animation",
    href: "/fuse/home",
  },
  {
    animationName: "Tab item layout animation",
    appName: "Google Chrome",
    slug: "google-chrome-tab-item-layout-animation",
    href: "/google-chrome/tabs",
  },
  {
    animationName: "Footer animation",
    appName: "Google Chrome",
    slug: "google-chrome-footer-animation",
    href: "/google-chrome/tabs",
  },
  {
    animationName: "Header background animation",
    appName: "Google Chrome",
    slug: "google-chrome-header-background-animation",
    href: "/google-chrome/tabs",
  },
  {
    animationName: "Home search transition animation",
    appName: "Raycast",
    slug: "raycast-home-search-transition-animation",
    href: "/raycast/home",
  },
  {
    animationName: "Home header tabs animation",
    appName: "Threads",
    slug: "threads-home-header-tabs-animation",
    href: "/threads/home",
  },
  {
    animationName: "Bottom tab bar and fab animation",
    appName: "Gmail",
    slug: "gmail-bottom-tab-bar-and-fab-animation",
    href: "/gmail/inbox",
  },
  {
    animationName: "Home tabs transition animation",
    appName: "Fuse",
    slug: "fuse-home-tabs-transition-animation",
    href: "/fuse/home",
  },
  {
    animationName: "Balance change toggle animation",
    appName: "Fuse",
    slug: "fuse-balance-change-toggle-animation",
    href: "/fuse/home",
  },
  {
    animationName: "Achievements carousel animation",
    appName: "Github",
    slug: "github-achievements-carousel-animation",
    href: "/github/achievements",
  },
  {
    animationName: "Pagination dots animation",
    appName: "Instagram",
    slug: "instagram-pagination-dots-animation",
    href: "/instagram/home",
  },
  {
    animationName: "Header scroll animation",
    appName: "Gmail",
    slug: "gmail-header-scroll-animation",
    href: "/gmail/inbox",
  },
  {
    animationName: "Profile picture animation",
    appName: "Threads",
    slug: "threads-profile-picture-animation",
    href: "/threads/profile",
  },
  {
    animationName: "Custom switch animation",
    appName: "Queue",
    slug: "queue-custom-switch-animation",
    href: "/queue/preferences",
  },
  {
    animationName: "Header transition animation",
    appName: "Canva",
    slug: "canva-header-transition-animation",
    href: "/canva/projects",
  },
  {
    animationName: "Home header marquee animation",
    appName: "Adidas",
    slug: "adidas-home-header-marquee-animation",
    href: "/adidas/home",
  },
  {
    animationName: "Profile header title animation",
    appName: "Github",
    slug: "github-profile-header-title-animation",
    href: "/github/profile",
  },
  {
    animationName: "Welcome screen animation",
    appName: "Apple Invites",
    slug: "apple-invites-welcome-screen-animation",
    href: "/apple-invites/welcome",
  },
  {
    animationName: "Top tabs indicator animation",
    appName: "Google Chrome",
    slug: "google-chrome-top-tabs-indicator-animation",
    href: "/google-chrome/tabs",
  },
  {
    animationName: "Header large title animation",
    appName: "WhatsApp",
    slug: "whatsapp-header-large-title-animation",
    href: "/whatsapp/communities",
  },
  {
    animationName: "Updates screen header animation",
    appName: "WhatsApp",
    slug: "whatsapp-updates-screen-header-animation",
    href: "/whatsapp/updates",
  },
  {
    animationName: "Add status background animation",
    appName: "WhatsApp",
    slug: "whatsapp-add-status-background-animation",
    href: "/whatsapp/updates",
  },
  {
    animationName: "Header large title animation",
    appName: "Viber",
    slug: "viber-header-large-title-animation",
    href: "/viber/calls",
  },
  {
    animationName: "Card blurry circles animation",
    appName: "ColorsApp",
    slug: "colorsapp-card-blurry-circles-animation",
    href: "/colorsapp/home",
  },
  {
    animationName: "Home header animation",
    appName: "ColorsApp",
    slug: "colorsapp-home-header-animation",
    href: "/colorsapp/home",
  },
  {
    animationName: "Calls top tabs animation",
    appName: "Viber",
    slug: "viber-calls-top-tabs-animation",
    href: "/viber/calls",
  },
  {
    animationName: "Chats header animation",
    appName: "Viber",
    slug: "viber-chats-header-animation",
    href: "/viber/chats",
  },
  {
    animationName: "Blurred header image animation",
    appName: "Luma",
    slug: "luma-blurred-header-image-animation",
    href: "/luma/discover-city",
  },
  {
    animationName: "Header on scroll animation",
    appName: "Linkedin",
    slug: "linkedin-header-on-scroll-animation",
    href: "/linkedin/home",
  },
  {
    animationName: "Top tabs indicator animation",
    appName: "X",
    slug: "x-top-tabs-indicator-animation",
    href: "/x/home",
  },
  {
    animationName: "Home header animation",
    appName: "X",
    slug: "x-home-header-animation",
    href: "/x/home",
  },
  {
    animationName: "Menu buttons animation",
    appName: "Apple Books",
    slug: "apple-books-menu-buttons-animation",
    href: "/apple-books/book",
  },
  {
    animationName: "Color picker background animation",
    appName: "ColorsApp",
    slug: "colorsapp-color-picker-background-animation",
    href: "/colorsapp/color-picker",
  },
  {
    animationName: "Palette picker color change animation",
    appName: "ColorsApp",
    slug: "colorsapp-palette-picker-color-change-animation",
    href: "/colorsapp/palette-picker",
  },
  {
    animationName: "Navigation between boards animation",
    appName: "Pinterest",
    slug: "pinterest-navigation-between-boards-animation",
    href: "/pinterest/home",
  },
  {
    animationName: "Pull to refresh loading animation",
    appName: "Pinterest",
    slug: "pinterest-pull-to-refresh-loading-animation",
    href: "/pinterest/home",
  },
  {
    animationName: "Story controls animation",
    appName: "Instagram",
    slug: "instagram-story-controls-animation",
    href: "/instagram/add-content",
  },
  {
    animationName: "Floating action button animation",
    appName: "X",
    slug: "x-floating-action-button-animation",
    href: "/x/home",
  },
  {
    animationName: "Bottom tabs background animation",
    appName: "X",
    slug: "x-bottom-tabs-background-animation",
    href: "/x/home",
  },
  {
    animationName: "Button tabs indicator animation",
    appName: "Linear",
    slug: "linear-button-tabs-indicator-animation",
    href: "/linear/home/dev-issues",
  },
  {
    animationName: "Bottom tabs indicator animation",
    appName: "Linkedin",
    slug: "linkedin-bottom-tabs-indicator-animation",
    href: "/linkedin/home",
  },
];
